common:
    exp_name: crw_resnet18_s3
   
    # Model related
    model_type: crw
    remove_layers: []
    im_mean: [0.4914, 0.4822, 0.4465]
    im_std: [0.2023, 0.1994, 0.2010]
    nopadding: False
    head_depth: -1
    resume: 'weights/crw.pth'
    
    # Misc
    down_factor: 8
    infer2D: True 
    workers: 4
    gpu_id: 0
    device: cuda

mot:
    obid: 'det'
    mot_root: 'C:/Users/Philip Fu/datasets/ap'
    seqs: ['201907251018_darshan_lane48', '201907251032_darshan_lane48', '201907251047_darshan_lane47', '201907251053_darshan_lane47', '201907251056_darshan_lane47', '201907251100_darshan_lane47', '201907251103_darshan_lane47', '201907251115_darshan_lane46', '201907251118_darshan_lane46', '201907251121_darshan_lane46']
    feat_size: [28, 28]
    save_videos: True
    save_images: False
    data_set_type: 'train'
    track_buffer: 150
    min_box_area: 200
    nms_thres: 0.4
    conf_thres: 0.0
    iou_thres: 0.5
    dup_iou_thres: 0.15
    confirm_iou_thres: 0.9
    img_size: [1920, 1080]
    prop_flag: False
    use_kalman: True 
    asso_with_motion: True 
    motion_lambda: 0.98
    motion_gated: True
    area_gated: True
    area_diff_threshold: 0.3
    assign_thres: 0.80
    category_gated: False
    calculate_metrics: True
    reactivate_on_edge: True
    eval_only: False
    eval_prod: False
    center_percent: 0.85
    feature_on_frame: True
    distance_name: 'rsm'